# Generated by Django 5.1.4 on 2025-04-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_size',
        ),
    ]
