# Generated by Django 5.0.1 on 2024-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='number_of_person',
            field=models.IntegerField(),
        ),
    ]
