# Generated by Django 5.0.1 on 2024-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_alter_catering_number_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='catering_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
