# Generated by Django 5.0.1 on 2024-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_catering_catering_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='catering_type',
            field=models.CharField(choices=[('wedding', 'Breakfast'), ('birthday', 'Birthday Catering'), ('holiday', 'Holiday Catering'), ('corporate', 'Corporate Catering'), ('private', 'Private Party Catering'), ('event', 'Event Catering'), ('buffet', 'Buffet Catering')], max_length=10),
        ),
    ]
