# Generated by Django 5.1.4 on 2025-04-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('order_phone', models.CharField(blank=True, max_length=13)),
                ('order_username', models.CharField(blank=True, max_length=50, null=True)),
                ('order_address', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_total_prices', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('complete', 'Completed')], default='received', max_length=20)),
                ('outTradeNo', models.CharField(editable=False, max_length=60)),
                ('transaction_no', models.CharField(blank=True, max_length=60)),
                ('referral_code', models.CharField(blank=True, max_length=30)),
                ('order_key', models.CharField(editable=False, max_length=6, unique=True)),
                ('paid_by_points', models.BooleanField(default=False)),
                ('paid_by_telebirr', models.BooleanField(default=False)),
                ('paid_by_bank', models.BooleanField(default=False)),
                ('bank_ref_number', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
