# Generated by Django 5.1.4 on 2025-04-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bank_ref_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total_prices',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outTradeNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_by_bank',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_by_points',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_by_telebirr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_no',
        ),
    ]
